# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eb15674c8c091f091f4f57169177a0bb78d86bbb6244c0ec102ff0ed4ca50dad6521926b3f2c024a4d35321b3b981a01ee07b7a98b6e8652b7dd6dc1e02c862

test:
  secret_key_base: a3c1113fd0e453ee516e140dd548f446dc0ce0fe919dbce94626800b21f77ba92e46f936503f9faf60f46fa09c82a270d465077983b03dc19184f7e38e42f16c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
